### PR TITLE
 Fix segfaults, decrease audio jitter, decrease CPU load, use structs, add proper ds cropping

### PR DESCRIPTION
**Pull request by Lorenzooone**
Fixes segfaults when closing the application, bad memory accesses, and a race condition when accessing curr_in (which caused issues when removing -O3/Ofast, so now the program will work fine even without that flag).

Reintroduces part of the old audio code (and fixes issues with it, while keeping it in a separate thread), as the new one could enter a loop of going over itself multiple times, causing it to never converge and keep doing "crunchy sounds".

Makes it so if the audio output is changed, the audio is restarted properly.

Introduces properly timed sleeps which decrease the total CPU load, and reduces audio and video jitter.

Creates "USB disconnect" safe settings, which are disabled by default, but are available for usage with macros.

Adds proper DS mode cropping (to activate proper DS mode, hold start while launching a DSi title or DS cartridge. This will make it so the game is launched in pixel perfect mode, without any blurring/cropping).

Creates struct for screen info which can be loaded/saved, to make it easier to load/save them.

### CODE REVIEW

**Comment by ChrisMalnick** [comment]
Hey again, just wanted to say I'm impressed to see just how much work you've been up to here since I didn't get to see it last time. I really do appreciate the interest and all the work you've put in here. Based on the description and the titles of the individual commits, it sounds like you've managed to do a lot of interesting stuff that I'm really looking forward to checking out! Coincidentally, I worked on an update just today that added in the native DS cropping like you've mentioned here (I didn't even know it existed myself until it was mentioned to me recently, and I could have saved some time too had I just came here first :P), but the updates weren't nearly as significant as last time so it shouldn't be a problem.

I haven't actually checked out your code changes yet though, but the first thing I'd like to do is just try to compile and run it as is to see how it goes. One of the things I'm very interested in is reintroducing the ability to "close" the device (either by disconnecting the cable or otherwise) since I had to remove it previously. Regarding sleep, I had put it in just as a blocking statement (it could have been literally anything like a print statement that doesn't print anything), but I'm actually a bit wary of using sleep since it's implemented differently across systems, and I haven't looked into how it's implemented within SFML itself yet. In any case, I'd like to see how it performs along with your other changes, so I'll be taking a look hopefully sometime soon, and I'll get back to you as soon as I've had a thorough run through. Anyway, until then, thanks again for all the hard work! Cheers!

**Comment by Lorenzooone** [comment]
Well, let me know and I can run a rebase to make the changes fit the update for a nice merge in.

**Comment by ChrisMalnick** [comment]
I'm really sorry I haven't gotten to this yet. I've been unexpectedly busy for the past couple of weeks and was away from home for a while. I managed to modify the Makefile while I was gone since I actually had limited access to a Mac and was also able to address #9, at least in part, since I didn't really need my 3DS with me to test it out. I was really hoping to start addressing this pull request today since I have access to my computer and 3DS again, but things really haven't been going as planned for me lately unfortunately. I did skim through your changes just a little while ago, and there's a lot to take in. Being that it might take me quite a while to thoroughly parse though this and that I'm already so behind on it, I'm now committed to really diving into it starting tomorrow. Even if I don't manage to get through everything tomorrow like I intend, I'll at the very least provide the feedback that I have and will continue to follow up on it in the coming days. Thanks for your patience here and again for all of your efforts.

**Comment by ChrisMalnick** [comment]
Okay, so over the past day, I've reconsidered what the best approach would be to handling the known issues that may have been addressed in your pull request. Specifically, I've decided to require the previous version of the D3XX driver (1.0.5) for this program. After I had previously upgraded to the latest version (1.0.14), the program had started responding differently, particularly experiencing segfaults related to device IO. Figuring I had no choice but to support the latest version of the driver since the previous version didn't even seem to be available anymore, I tried a number of reasonable things to circumvent these issues, but ultimately decided to just cut my losses.

Now that I know the latest version of the driver is actually outright bugged and have come up with a way to install the previous version of the driver via the Makefile, I feel a lot more comfortable requiring it for full support. For me, It doesn't seem practical to change the codebase to work around bugs in a dependency that should just be ultimately fixed by the maintainers themselves, especially since as far as I know, the driver itself is proprietary, considering that it's distributed as precompiled libraries and only exposed via header files. Assuming that this is fixed in the future, the latest version of the driver will be used again and shouldn't require any unnecessary code changes like the current version does.

That all being said, I don't want to have to introduce code that doesn't server a practical purpose or doesn't lead to significant enough performance gains. It may be a lot of me to ask, but would you be able to run the current version of the code with the previous version of the driver just to see exactly what issues may still be present. It's hard for me to get a handle on what might be occurring on other systems, particularly macOS (not sure if that's what you happen to be using), since I'm running on 8+ year old hardware. Being that this program was designed to allow external capture/recording, it would be especially helpful if you could provide an example of what it is that you might be experiencing.

Again, I'm really sorry for the big ask and to have undercut the work you've done, though some of it may still be of use, assuming that there are remaining issues. Don't feel compelled to have to do anything though, and feel free to take your time if you do decide to do it. Sorry for being overly meticulous about this, I can be a bit of a stickler as is, but knowing that there's an extraneous issue at hand, I really just want to make sure that it's eliminated from consideration before making any significant changes.

**Comment by Lorenzooone** [comment]
Hi, most of the issues I've fixed stem from logical errors.
There are some (the ones which were the most annoying) which get fixed by swapping the driver, so I've added a commit to remove them.

The other ones remain.

I've rebased the code.
Not only that, I fixed an issue I have with the new makefile, which was actually more of an install command.

I separated the two processes, as someone may not want to give sudo access to a script they don't trust, and they may just want to simply build the program. This should now work better for the end users.

**Comment by Lorenzooone** [comment]
Changed the way xx3dsfml is build to statically link FTD3XX instead.
This significantly lowers the amount of priviliges which must be given to make, and makes it so building for users should be easier.

**Comment by ChrisMalnick** [comment]
Okay, so I've finally gotten around to testing out the changes a bit. I started doing a little regression testing, but quickly noticed there was something wrong with my code's performance. I realized I had mistakenly removed the sleep statements from the playback and render methods during one of my previous updates and had forgotten to put them back in. This being the case, if you did actually run my code recently, it would have have suffered from noticeably worse performance.

Anyway, after patching that back in, I continued with the regression testing, and these were my findings:
- There was a decrease in CPU temp by ~5C with the changes despite no conclusive difference in CPU usage or load avg.
```
 CPU TEMP LOAD  RAM |  GPU TEMP VRAM
~10% ~50C ~15% ~13% | ~15% ~60C ~11%
~10% ~45C ~15% ~13% | ~15% ~60C ~11%
```
For both, the load would spike occasionally, but it looked to get higher (low 30% vs high 20%) and stay higher for longer with the changes. It's really hard to get a handle on this sort of thing though. I basically just let the 3DS idle on the title screen of a game for several minutes several times with and without the changes while having minimal things running in the background. This is by no means empirical, but it's hard to test this sort of thing out reliably unfortunately.

Anyway, the decrease in CPU temp is nice, but it seems to come at a cost.
- There was a noticeable increase in audio latency where it would fall out of sync relatively quickly and never recover (unless stopping and starting the audio again) when running with the changes.

Other than this, there were some insignificant differences that I'll list here for completeness:
- The audio artifacts differently when restarting capture, but takes longer to stabilize with the changes.
- The screen isn't blanked when the 3DS is disconnected with the changes.

With all that being said, I'm not convinced that this is enough of a performance benefit to justify losing out on accuracy to this extent. To me, the order of importance when it comes to this software would be the overall stability > the overall accuracy > the overall performance. Since I haven't experienced any issues with stability outside of the faulty driver, I'm hesitant to move any further on this at the moment to be honest.

You've said that there were other issues outside of the driver problem, but I haven't experienced them to even weigh in on it, and as far as I'm concerned, they would have to be significant enough to justify the noticeable increase in audio latency.

**Comment by Lorenzooone** [comment]
The audio issue is weird.
In fact, I had that exact issue before I made the changes, not after.
Are you sure that you were considering the right version as the new one?

If you are, try changing
#define AUDIO_LATENCY 4
to
#define AUDIO_LATENCY 5
and let me know what happens.

**Comment by Lorenzooone** [comment]
Update: Switched to proper waits instead of sleeps. Let me know if this fixes the issue you were having.

**Comment by Lorenzooone** [comment]
Anyways, here is a list of the changes:
- Changed the Makefile. Now only install will require sudo. Normal building won't. download_ftd3xx will download a version of ftd3xx which will be statically linked.
- Fixed issue where closing USB connection was problematic due to unreleased resources.
- Fixed issue where opening/closing USB connection too fast was problematic. I know you "prevented" it by making it so keystrokes are not repeated. However, that is just hiding the issue (and it is annoying if you have to turn up the volume).
- Fixed various issues where opening USB connections would sometimes show weird image artifacts. Some were general issues, others only happen with the "old" ft3dxx version of the driver which the software is currently using.
- Switched Audio to its own thread, instead of being global. Allows for easier manipulation (specifically for the next point).
- Made it so the audio buffer won't go over itself if there is some temporary issue with lag (like at the beginning of a connection). This is why the new code is slower to converge to a "proper audio". It's because it's not going over itself multiple times (which is problematic behaviour).
- Made it so if you switch the audio output, the sound won't just stop working entirely.
- Added struct to use for loading/saving ScreenInfo in a more generic way. Instead of global pointers to private Class members. Makes for easier saving/loading per screen.
- Added some load/save input sanitization.
- Improved performance (new to the last commit) by waiting on resources to become available instead of using sleeps, which are OS dependent and may lead to lag in video/audio on certain systems.

**Comment by Lorenzooone** [comment]
Added a commit to prevent vSync on split mode.
If one of the two windows goes out of view (by having something obscure it), vSync will stop working properly, and it will lag the other window significantly. This doesn't happen when minimizing the window. Only if it's obscured by something going over it.

**Comment by ChrisMalnick** [comment]
I tested your newest changes out against my recent additions and found them to be pretty comparable now in both performance and accuracy. Between that and the more thorough explanations you've provided for the changes, I'm pretty satisfied now.

The code is significantly different now though, so I'd just like to review it more closely before merging it in. Having skimmed through it again just now though, I've noticed some nice additions already, but it does seem to have stepped up in complexity. The more I can familiarize myself with it the better, so I may come back with some questions along with my general feedback. I'll try my best to get to it as soon as I can, which hopefully will be much quicker than the last time I said that!

**Comment by Lorenzooone** [comment]
Btw, there may be issues on macOS with the executable, as it is not officially signed by an Apple authorized developer.
I think linking to this in the readme may be the best course of action: https://docs.brew.sh/FAQ#why-cant-i-open-a-mac-app-from-an-unidentified-developer

**Comment by ChrisMalnick** [comment]
Hey buddy, I've just got a quick update for you this time. In the midst of seeing the additional changes here and being generally dissatisfied with SFML's SoundStream implementation, I decided to reassess the fundamental structure of the code. In doing this, I attempted to replace the audio playback with something more custom. Even though I was able to get the audio in sync with the 3DS, I wasn't able to ensure its own continuity with itself unfortunately. It's a shame too since it seemed really promising, but hopefully there will be some updates to SFML in the future that will allow me to reattempt this.

In any case though, I've decided to continue with restructuring the code anyway since it aligns better with the intent of the software in the first place, and it should also hopefully address some of the previous issues by streamlining the way in which some of the processing is approached. It's still a work in progress, but I figured I'd let you know ahead of time.

Typically, I work on these updates pretty abruptly when I find myself having enough time to actually sit down and commit to it, and I'm usually able to push them out pretty much within the same sitting. This time around though, my focus has been pretty intermittent on it, and between that and actually wanting to get some thorough testing in for once, it may be a little while before I actually get to push it out. Anyway, just wanted to let you know what my intentions are. One thing lead to another, and before I knew it, I was working on things that I hadn't even plan to. It should all hopefully be for the better though.

**Comment by Lorenzooone** [comment]
Hey, that's fine and all, take your time. However could I ask you to fix the missing License issue? https://github.com/ChrisMalnick/xx3dsfml/issues/10 It shouldn't take long.
Thanks!

**Comment by Lorenzooone** [comment]
Actually, by making use of some of the things I introduced in the PR (the proper waiting, instead of using a sleep), I was able to remove the audio buffer. It's not perfect-perfect, but it's pretty close...
You may want to look into it...

**Comment by ChrisMalnick** [comment]
Hey there, sorry again for all the waiting. My intentions of restructuring the code didn't go as fully as I would have hoped. I was once again thwarted by SFML, this time due to how it handles OpenGL contexts behind the scenes. It really made me consider switching to using OpenGL directly itself since I already have enough experience with it, but it's probably not worth the effort.

Anyway, I still significantly restructured the code, just not as much as I was originally planning to. I think it's a lot more intentional with what it's accomplishing now and is more direct in how it accomplishes it. Performance seems to be pretty equivalent still though which is fine since it's not bad in the first place. I'm figuring that running the asynchronous D3XX buffers is really what requires the most amount of resources at this point which probably would only improve with updates to the driver.

The audio is also probably as good as it's going to get. Short of SFML making any major updates to help with the latency, I think whatever oddities still exist with the audio come down to the capture board and the 3DS itself. I think this is also fine though, it's really only in specific edge cases where it occurs, and the latency, while still noticeable, really isn't all that bad.

I get the feeling that eking out any more performance would require a lot of over engineering and probably with little to no gain at that. I really think it's up to the underlying frameworks to update at this point, but even then, l still think some of it just comes down to the capture board and the 3DS.

Moving on, the only other things I wanted to address here have to do with the Makefile.

I saw that you switched over to using the statically linked D3XX library. This was something that I also had considered at a time but decided not to do for a few reasons. The first being that SFML is dynamically linked as it is, so it's not like you can locally contain all of the dependencies in the binary anyway. Secondly, since the dynamically linked library is readily available, I think it should be taken advantage of, and I myself find it very convenient to have. Lastly, the binary is already going in the /usr/local directory, so putting additional files there really isn't a bid deal and is fairly standard for this kind of use case. The binary is also smaller this way, but it's so insignificant in this case that I wouldn't even consider it a good reason.

Anyway, touching on the last legitimate point there, I removed all uses of sudo from the Makefile. If a make command might need root access, it should be up to the user to run it that way. For some users, they may already have root access. For others, they may not even need root access. Using sudo/doas/etc. directly on a make command when needed is fairly standard, especially on install commands, and is something I've seen done quite a lot myself, so it really shouldn't be something of a huge concern.

The last thing I wanted to touch on was already mentioned in #12, and it's having to do with handling brew directly. I'm still on the fence about this since at what point should it end? Should something like flatpak be supported too? What about snaps and appimages? I don't actually know if SFML is available in any of those as of now, but the point still stands. Brew isn't a requirement for Mac users, it's just a suggestion, so that's something that I'll have to think over some more before I come to any definitive conclusion.

Okay, so I ended up writing a lot here... Sorry about that! There's a lot more that I could talk about honestly, but I'll leave it at that. Though, I will end in saying that if you ever wanted to have a more direct discussion about any of this, I'd be more than happy to, so just let me know!

**Comment by Lorenzooone** [comment]
Hey, the branches are way too different now to merge back.
Hopefully you addressed some of the things I previously changed. Feel free to "cannibalize" code from https://github.com/Lorenzooone/xx3dsfml/tree/new_main_changes if not.
If any user complains about building/running the application, feel free to link them to that as well.

If you have issues with SFML, SDL2 may work...? Just a suggestion.

If you want to talk, I'm lorenzooone on Discord.

I'll be removing the rest of your code from what I have right now (to avoid licensing issues) and I'll work on my own version of the software, since it seems we have different goals, and I've already heavily altered your original source (I'm more interested in using the software to play on the TV).

Best of luck with this!

**Pull request closed without merging**
